# 应用名称
spring:
  application:
    name: springboot_mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webwork?serverTimezone=UTC
    username: root
    password: 200621

#
##下面这些内容是为了让MyBatis映射
##指定Mybatis的Mapper文件
#mybatis.mapper-locations=classpath:mappers/*xml  #classpath：在resource目录中找
##指定Mybatis的实体目录
#mybatis.type-aliases-package=com.zjh.mybatis.entity  #mapper.xml文件中resultMap的type、parameterType、resultType会引用一些实体类，我们需要写上全限定类名，如果不写全限定类名，只写一个实体类的名称的话，那就需要在application.yml文件中设置mybatis:type-aliases-package参数；

