server:
  port: 9000

spring:
  activemq:
    broker-url: tcp://localhost:61616
  jms:
    template:
      default-destination: zjh
    pub-sub-domain: true   #发布订阅
  rabbitmq:
    host: localhost
    port: 5672
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order

rocketmq:
  name-server: localhost:9876
  producer:
    group: group_rocketmq
