# 应用名称
spring:
  application:
    name: springboot_mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webwork?serverTimezone=UTC
    username: root
    password: 200621


#设置Mp相关的配置
