server:
  port: 9002
  servlet:
    context-path: /ssmpDemo


spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/webwork?serverTimezone=UTC
      username: root
      password: root
  boot:
    admin:
      client:
        url: http://localhost:9000

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

test:
  value: 800


management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"